---
- name: Create Docker Swarm TLS directory
  file:
    path: "{{ docker_swarm_tls_dir }}"
    state: directory

- name: Create Docker Swarm ca.pem
  copy:
    content: "{{ docker_swarm_tls_ca_cert }}"
    dest: "{{ docker_swarm_tls_dir }}ca.pem"

- name: Create Docker Swarm cert.pem
  copy:
    content: "{{ docker_swarm_tls_cert }}"
    dest: "{{ docker_swarm_tls_dir }}cert.pem"

- name: Create Docker Swarm key.pem
  copy:
    content: "{{ docker_swarm_tls_key }}"
    dest: "{{ docker_swarm_tls_dir }}key.pem"
