laravel_app_name: ticketbeast

satis_host: satis
satis_username: test
satis_password: "{{ vault_satis_password }}"

github_token: "{{ vault_github_token }}"

docker_proxy_network_name: proxy_webgateway
docker_compose_project_name: ticketbeast
gitlab_project_path: tkoggel/ticketbeast

docker_swarm_tls_ca_cert: "{{ vault_docker_swarm_tls_ca_cert }}"
docker_swarm_tls_cert: "{{ vault_docker_swarm_tls_cert }}"
docker_swarm_tls_key: "{{ vault_docker_swarm_tls_key }}"

image_tag_php: 0.1.0
image_tag_nginx: 0.5.2
image_tag_mysql: 10.3.10-bionic
