---
- name: CI Build App
  hosts: ci_build_images
  gather_facts: no
  vars_files:
    - ../envs/000_cross_env_vars/vars.yml
    - ../envs/000_cross_env_vars/vault.yml
  roles:
    - envfiles
  tasks:
    - name: Login to Docker Registry
      docker_login:
        registry: registry.proserve.nl
        docker_host: tcp://127.0.0.1:2375
        username: "{{ lookup('env', 'CI_REGISTRY_USER') }}"
        password: "{{ lookup('env', 'CI_JOB_TOKEN') }}"
