---
- name: Create envfiles dest dir
  file:
    path: "{{ envfiles_dest }}"
    state: directory
  when: envfiles_create_dest_dir

- name: Append envfiles_templates_append to envfiles_templates
  set_fact:
    envfiles_templates: "{{ envfiles_templates + envfiles_templates_append }}"
  when: envfiles_templates_append | length > 0

- name: Creating files
  template:
    src: "{{ item.src }}"
    dest: "{{ envfiles_dest }}/{{ item.dest }}"
    force: "{{ envfiles_force }}"
  with_items: "{{ envfiles_templates }}"
